language: node_js

node_js:
  - 'node'

before_install:
  - npm i -g npm@latest

install:
  - npm ci

cache:
  directories:
    - node_modules

script:
  - bin/fetch-configlet && bin/configlet lint --track-id reasonml .
  - make
  - make clean
