---
name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - ".gitignore"
      - "LICENSE"

jobs:
  build:
    name: Test Runner
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - name: Install reasonml
        run: npm install -g esy
      - name: Run tests
        run: ./bin/test-exercises.sh
        
